msvc++ compile fix. Fixes this error:
c:\users\thammer\code\checkout\Coin\src\base\SbMatrix.cpp(557) :
error C2440: 'type cast' : cannot convert from 'float (*)[4][4]'
to 'class SbMatrix'.
No constructor could take the source type, or constructor overload
resolution was ambiguous.

This is a FRE (Frequently Recurring Error, tm) in the SbMatrix.cpp file.
I'm a bit surprised gcc doesn't complain.